import Head from "next/head";
import StudentFillingBidPage from "@/src/components/page_components/student_pages/student_filing_bid_page";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function StudentApplicationCreate() {
  return (
    <>
      <Head>
        <title>Подача заявления</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <StudentFillingBidPage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
