import Head from "next/head";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSideProps } from "next";
import StudentFormPage from "@/src/components/page_components/student_pages/student_form_page";

export default function StudentApplicationEdit() {
  //TODO:handle application_id with server_side_props
  return (
    <>
      <Head>
        <title>Подача заявления</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <StudentFormPage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
