import ApplicationPage from "@/src/components/page_components/admission_pages/application_list_page/application_page";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";

export default function AdmissionApplicationListApplicationMain() {
  return (
    <>
      <Head>
        <title>Персональные данные</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ApplicationPage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
