import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Список факультетов и направлений</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
}
