import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import AuthRegistrationPage from "@/src/components/page_components/auth_pages/auth_registration_page";
import Head from "next/head";

export default function Registration() {
  return (
    <>
      <Head>
        <title>Регистрация</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AuthRegistrationPage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
