import FacultyIdListPage from "@/src/components/page_components/admission_pages/admission_student_list_page/faculty_id_list_page";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";

export default function AdmissionStudentListFacultyId() {
  return (
    <>
      <Head>
        <title>Факультет</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FacultyIdListPage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
