import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import AdmissionStudentListPage from "@/src/components/page_components/admission_pages/admission_student_list_page";
import Head from "next/head";

export default function AdmissionStudentList() {
  return (
    <>
      <Head>
        <title>Список абитуриентов</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AdmissionStudentListPage />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
