import Head from "next/head";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function Home() {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
}

{
  /* <div>
        <StatusIndicator type="new" title="новое" />
        <StatusIndicator type="returned" title="возвращено" />
        <StatusIndicator type="Invited" title="приглашено" />
        <StatusIndicator type="repeated" title="повторное" />
        <StatusIndicator type="waiting" title="Ожидающий" />
        <StatusIndicator type="approved" title="Одобрено" />
        <StatusIndicator type="pending" title="В ожидании" />
        <StatusIndicator type="incomplete" title="Неполный" />
        <StatusIndicator type="rated" title="Оценен" />
        <StatusIndicator type="notCome" title="Не пришел" />
        <StatusIndicator type="sent" title="Отправил" />
        <StatusIndicator type="paid" title="Оплаченный" />
        <StatusIndicator type="rejected" title="Отклонено" />
      </div> */
}

/*
  - student
    -- index.tsx (main page)
    -- application
      -- index.tsx (create)
      -- edit.tsx (edit)
    -- about_university
      -- index.tsx

  
  - admission ( {BASE_URL}/admission -> {BASE_URL}/admission/applications_list )
    -- applications_list
      -- index.tsx (main page)
      -- application
        -- index.tsx (personal data)
        -- history.tsx (history)
    -- exams_list
      -- index.tsx (main page)
    -- students_list
      -- index.tsx (main page)
      -- [faculty_id]
        -- index.tsx (list)
        stundent_info (404)
          -- [student_id].tsx (stundet info page)


  - marketing
    -- index.tsx (main_page)
    -- students_list
      -- index.tsx


  - accounting
    -- index.tsx (main page = students list)
    -- student_info
      -- [stundet_id].tsx (student info)
  
  
  - admin
    -- index.tsx (main page)
    -- create_faculty.tsx
*/

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
